### ISSUE TITLE
طلب مساعدة

### ISSUE THREAD

**Issue by kingman29** [MrAbdelaziz/MrAbdelaziz#1]
السلام عليكم 
أنا اسمي خالد من الجزائر
أولا أود أن أشكرك على ما تقدمه وفي ميزان حسناتك 
سؤالي متعلق ب تطبيق ويب تسيير مخزون الخاص
بك 
بصفتي مبتدأ ماذا يجب علي أن أثبت لكي أتمكن من تشغيل التطبيق من فضلك

**Comment by MrAbdelaziz** [comment]
salam Khalid,
tu peux me joindre sur google meet :

Wednesday, December 29 · **16:00 – 17:00**
Google Meet joining info
Video call link: https://meet.google.com/voi-ykjd-sij

**Comment by MrAbdelaziz** [comment]
Salam khalid ,
9oli li fin 7eslti ana m3ak !
